sitewide_alert.settings:
  type: config_object
  label: 'Sitewide alert settings'
  mapping:
    show_on_admin:
      type: 'integer'
      label: 'Show on Administration Pages'
    alert_styles:
      type: 'string'
      label: 'Available alert styles'
    refresh_interval:
      type: 'integer'
      label: 'Browser Refresh Interval (in seconds)'
    automatic_refresh:
      type: 'integer'
      label: 'Automatically update (Refresh) Alerts'
